#!/bin/sh

THIS_SCRIPT=$0

if [ -L "$THIS_SCRIPT" ]; then
  THIS_SCRIPT=`readlink "$THIS_SCRIPT"`
fi

SCRIPT_DIR=`dirname "$THIS_SCRIPT"`
PROJ_DIR="$SCRIPT_DIR/.."
PUILD="$SCRIPT_DIR/puild"

$PUILD "$PROJ_DIR/src" ---p $* ---o ri

